export const SLIDER_CONSTANTS = {
  DRAG_RESISTANCE: 0.4,
  SWIPE_THRESHOLD_PERCENT: 0.08,
  VELOCITY_THRESHOLD: 0.3,
  WHEEL_RESISTANCE: 0.3,
  WHEEL_SCROLL_THRESHOLD: 120,
  WHEEL_RESET_DELAY: 150,
  MOMENTUM_EASING: 0.1,
  ANIMATION_TIMEOUT: 800,
}

export const DEFAULT_COLORS = ["#F5F4F0", "#E5E4E0", "#D5D4D0"]
